[package]
name = "password_hashing_bcrypt_pbkdf"
version = "0.1.0"
authors = ["HuangJian <1342042894@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bcrypt-pbkdf = "0.4.0"
