[package]
name = "lifetime"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "strtok"
path = "src/strtok.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
