[package]
name = "password_hashing_pbkdf2"
version = "0.1.0"
authors = ["HuangJian <1342042894@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pbkdf2 = "0.6.0"
hmac = "0.10"
sha-1 = "0.9"
sha2 = "0.9"


