[package]
name = "sqlx_todos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-std = { version = "1.8.0", features = [ "attributes" ] }
futures = "0.3"
paw = "1.0"
sqlx = { version = "0.6.0", features = ["sqlite", "runtime-async-std-native-tls"] }
structopt = { version = "0.3", features = ["paw"] }
