[package]
name = "webgl2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
yew = "0.19"
gloo-render = "0.1"
anyhow = "1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
nalgebra = "0.30.1"
rand = "0.8.4"
getrandom = { version = "0.2.4", features = ["js"] }

[dependencies.web-sys]
version = "0.3"
features = [
  'HtmlCanvasElement',
  'WebGlBuffer',
  'WebGlProgram',
  'WebGl2RenderingContext',
  'WebGlShader',
  'WebGlUniformLocation',
  'WebGlVertexArrayObject',
  'CanvasRenderingContext2d',
]

[build-dependencies]
anyhow = "1"