[package]
name = "ecc_k256_ecdh"
version = "0.1.0"
authors = ["HuangJian <1342042894@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k256 = { version = "0.7.1", features = ["ecdh"] }
rand_core = { version = "0.6.0", features = ["getrandom"] }
