[package]
name = "openssl_01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "demo01"
path = "src/demo01.rs"

[[bin]]
name = "demo02"
path = "src/demo02.rs"

[[bin]]
name = "demo03"
path = "src/demo03.rs"

[dependencies]
anyhow = "1.0.72"
openssl = { version = "0.10", features = ["vendored"] }
openssl-sys = "0.9"
