[package]
name = "versioning"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.1.1"

async-trait = "0.1"
bytes = "1.0"
futures-util = "0.3"
http = "0.2"
http-body = "0.4"
hyper = { version = "0.14", features = ["full"] }
pin-project = "1.0"
regex = "1.5"
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.7"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.6"
tower = { version = "0.4", features = ["full"] }
tower-http = { version = "0.1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.2"
