[package]
name = "pxsem"
version = "0.1.0"
authors = ["HuangJian <1342042894@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
runpv22e = { path = "../runpv22e" }

libc = "0.2.71"
structopt = "0.3"
