[package]
name = "heapsize"
version = "0.1.0"
authors = ["huangjian <1342042894@qq.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapsize_derive = { path = "../heapsize_derive" }
