[package]
name = "sort_middleware_lib"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sort_lib = { path = "../sort_lib" }
random_data_lib = { path = "../random_data_lib" }
time = "0.1"
